# Homework 2

Collaborators: Edwin Tong, Kevin Shyam Sunder

In [1]:
!mkdir -p ./cpsc375 && wget --quiet --timestamping https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/cpsc375/__init__.py --output-document=./cpsc375/__init__.py

In [2]:
from cpsc375 import *

In [3]:
!pip install lets-plot

Requirement already satisfied: lets-plot in /usr/local/lib/python3.13/dist-packages (4.11.0)
Requirement already satisfied: pypng in /usr/local/lib/python3.13/dist-packages (from lets-plot) (0.20220715.0)
Requirement already satisfied: palettable in /usr/local/lib/python3.13/dist-packages (from lets-plot) (3.3.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from lets-plot) (11.3.0)

# Question 1
The following questions use the data collected from the anonymous survey collected at the beginning of the course and from previous semesters. The dataset can be downloaded from the Exploratory data analysis module on Canvas. Use the method read_csv() to load the data into a variable named survey.

Apply Pandas queries, manipulation, grouping, and aggregation to answer these questions. For each question, write the code as a single method chain with multiple “verbs” one after the other, beginning with survey.

In [4]:
import pandas as pd

survey = pd.read_csv('/content/surveydataFall2026.csv')
survey

,Semester,ComputerScience,Math,Statistics,MachineLearning,DomainExpertise,Communication,Visualization,TakenCPSC483,PlanCPSC483,MajorCS,FamiliarR,FamiliarPython
0,Fall2024,4,5.0,6.0,4.0,3,6,4,No,Yes,Yes,4,4.0
1,Fall2024,7,7.0,5.0,1.0,3,2,5,No,No,Yes,1,7.0
2,Fall2024,8,8.0,6.0,5.0,2,1,5,No,Yes,Yes,4,8.0
3,Fall2024,6,5.0,3.0,1.0,2,4,2,No,No,Yes,2,5.0
4,Fall2024,5,6.0,6.0,3.0,2,6,6,Yes,No,Yes,7,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,Fall2026,5,5.0,6.0,5.0,1,2,5,No,No,Yes,4,7.0
426,Fall2026,7,3.0,10.0,10.0,5,10,8,No,No,Yes,1,6.0
427,Fall2026,7,9.0,7.0,7.0,3,1,7,No,Yes,Yes,2,8.0
428,Fall2026,8,8.0,6.0,3.0,2,5,5,No,Yes,Yes,4,8.0
429,Fall2026,5,5.0,5.0,5.0,3,4,5,No,Yes,Yes,1,6.0

a. Show only rows where Statistics skill is 10

In [5]:
survey[survey['Statistics'] == 10]

,Semester,ComputerScience,Math,Statistics,MachineLearning,DomainExpertise,Communication,Visualization,TakenCPSC483,PlanCPSC483,MajorCS,FamiliarR,FamiliarPython
7,Fall2024,10,10.0,10.0,8.0,3,8,8,No,No,Yes,9,8.0
35,Fall2024,10,10.0,10.0,10.0,5,10,10,No,Yes,Yes,10,10.0
88,Spring2025,7,9.0,10.0,7.0,1,6,9,No,Yes,No,10,10.0
157,Fall2025,8,8.0,10.0,10.0,5,10,10,Yes,No,Yes,2,10.0
237,Fall2025,7,9.0,10.0,7.0,1,6,9,No,Yes,No,10,10.0
268,Spring2026,10,10.0,10.0,9.0,4,10,8,Yes,Yes,Yes,10,10.0
359,Fall2026,7,10.0,10.0,3.0,5,8,10,No,No,Yes,5,10.0
360,Fall2026,10,10.0,10.0,10.0,5,10,10,No,Yes,Yes,5,5.0
426,Fall2026,7,3.0,10.0,10.0,5,10,8,No,No,Yes,1,6.0

b. Show only rows where both Statistics and Math skills are 10

In [6]:
survey[(survey['Statistics'] == 10) & (survey['Math'] == 10)]

,Semester,ComputerScience,Math,Statistics,MachineLearning,DomainExpertise,Communication,Visualization,TakenCPSC483,PlanCPSC483,MajorCS,FamiliarR,FamiliarPython
7,Fall2024,10,10.0,10.0,8.0,3,8,8,No,No,Yes,9,8.0
35,Fall2024,10,10.0,10.0,10.0,5,10,10,No,Yes,Yes,10,10.0
268,Spring2026,10,10.0,10.0,9.0,4,10,8,Yes,Yes,Yes,10,10.0
359,Fall2026,7,10.0,10.0,3.0,5,8,10,No,No,Yes,5,10.0
360,Fall2026,10,10.0,10.0,10.0,5,10,10,No,Yes,Yes,5,5.0

c. Show only the Semester, Communication, and Visualization columns where both Statistics and Math skills are 10

In [7]:
survey.loc[survey['Statistics'] == 10, ['Semester', 'Communication', 'Visualization']]

       Semester  Communication  Visualization
7      Fall2024              8              8
35     Fall2024             10             10
88   Spring2025              6              9
157    Fall2025             10             10
237    Fall2025              6              9
268  Spring2026             10              8
359    Fall2026              8             10
360    Fall2026             10             10
426    Fall2026             10              8

d. Show only the Semester, Communication, and Visualization columns in decreasing order of Statistics and then Math skills

In [8]:
survey.sort_values(by=['Statistics', 'Math'], ascending=[False, False])

,Semester,ComputerScience,Math,Statistics,MachineLearning,DomainExpertise,Communication,Visualization,TakenCPSC483,PlanCPSC483,MajorCS,FamiliarR,FamiliarPython
7,Fall2024,10,10.0,10.0,8.0,3,8,8,No,No,Yes,9,8.0
35,Fall2024,10,10.0,10.0,10.0,5,10,10,No,Yes,Yes,10,10.0
268,Spring2026,10,10.0,10.0,9.0,4,10,8,Yes,Yes,Yes,10,10.0
359,Fall2026,7,10.0,10.0,3.0,5,8,10,No,No,Yes,5,10.0
360,Fall2026,10,10.0,10.0,10.0,5,10,10,No,Yes,Yes,5,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Fall2025,6,7.0,1.0,2.0,2,9,2,No,Yes,Yes,1,7.0
197,Fall2025,6,6.0,1.0,1.0,4,5,2,No,Yes,Yes,1,8.0
403,Fall2026,3,3.0,1.0,1.0,1,1,1,No,No,Yes,1,3.0
401,Fall2026,9,7.0,NaN,4.0,3,4,9,No,Yes,Yes,6,9.0
266,Spring2026,10,NaN,NaN,1.0,4,5,1,No,Yes,Yes,1,3.0

e. Show only rows where Statistics skill is missing

In [9]:
survey[survey['Statistics'].isnull()]

,Semester,ComputerScience,Math,Statistics,MachineLearning,DomainExpertise,Communication,Visualization,TakenCPSC483,PlanCPSC483,MajorCS,FamiliarR,FamiliarPython
266,Spring2026,10,NaN,NaN,1.0,4,5,1,No,Yes,Yes,1,3.0
401,Fall2026,9,7.0,NaN,4.0,3,4,9,No,Yes,Yes,6,9.0

f. Show for every student, only their Semester, Math skill, Statistics skill, and the maximum of their Math and Statistics skills (Hint: use axis=1)

In [10]:
survey.assign(MaxMathStats=survey[['Math', 'Statistics']].max(axis=1))[['Semester', 'Math', 'Statistics', 'MaxMathStats']]

     Semester  Math  Statistics  MaxMathStats
0    Fall2024   5.0         6.0           6.0
1    Fall2024   7.0         5.0           7.0
2    Fall2024   8.0         6.0           8.0
3    Fall2024   5.0         3.0           5.0
4    Fall2024   6.0         6.0           6.0
..        ...   ...         ...           ...
425  Fall2026   5.0         6.0           6.0
426  Fall2026   3.0        10.0          10.0
427  Fall2026   9.0         7.0           9.0
428  Fall2026   8.0         6.0           8.0
429  Fall2026   5.0         5.0           5.0

[430 rows x 4 columns]

g. Show the median value of Computer Science skills

In [11]:
(
    survey
    .agg({'ComputerScience': 'median'})
)

ComputerScience    7.0
dtype: float64

h. Show the median value of Computer Science skills in Fall 2025

In [12]:
(
    survey
    .query('Semester == "Fall 2025"')
    .agg({'ComputerScience': 'median'})
)

ComputerScience   NaN
dtype: float64

i. Show the median values of (each of) Computer Science, Math, and Statistics skills in every semester

In [13]:
(
    survey
    .groupby('Semester')
    .agg({'ComputerScience': 'median', 'Math': 'median', 'Statistics': 'median'})
)

            ComputerScience  Math  Statistics
Semester
Fall2024                6.0   7.0         6.0
Fall2025                7.0   7.0         6.0
Fall2026                7.0   7.0         7.0
Spring2025              7.0   7.0         6.0
Spring2026              7.0   7.0         6.0

j. Show the median values of (each of) Computer Science, Math, and Statistics skills in every semester of students who have taken CPSC483 (i.e. TakenCPSC483 is Yes)

In [14]:
(
    survey
    .query('TakenCPSC483 == "Yes"')
    .groupby('Semester')
    .agg({'ComputerScience': 'median', 'Math': 'median', 'Statistics': 'median'})
)

            ComputerScience  Math  Statistics
Semester
Fall2024                5.5   6.0         4.5
Fall2025                8.0   8.0         7.0
Fall2026                7.0   7.0         7.0
Spring2025              7.5   8.0         7.0
Spring2026              7.0   7.0         5.0

k. Show the median values of (each of) Computer Science, Math, and Statistics skills for groups of students who have taken and not taken CPSC483 (Hint: groupby)

In [15]:
(
    survey
    .groupby('TakenCPSC483')
    .agg({'ComputerScience': 'median', 'Math': 'median', 'Statistics': 'median'})
)

              ComputerScience  Math  Statistics
TakenCPSC483
No                        7.0   7.0         6.0
Yes                       7.0   7.0         7.0

l. Show the number of students who took the survey in every semester

In [16]:
(
    survey
    .groupby('Semester')
    .agg({'Semester': 'count'})
)

            Semester
Semester
Fall2024          55
Fall2025         149
Fall2026          88
Spring2025        62
Spring2026        76

# Question 2
Consider the two tables shown below called population and countyseats.

population:

 state		county       	year 	population
1 California	Orange	2000 	2846289   
2 California	Orange	2010 	3010232   
3 California	Los Angeles	2000 	3694820   
4 California	Los Angeles	2010 	3792621

countyseats:

 statename    	countyname	countyseat
1 California 	Orange      	Santa Ana  
2 California 	Los Angeles 	Los Angeles
3 California 	San Diego   	San Diego  
4 Oregon     	Wasco       	The Dalles

Draw the output table from the following operations. You may do this using Markdown tables, or by drawing the tables on paper and scanning and uploading your answer.

(Note: you should be able to calculate the following output by hand, though you are welcome to use Pandas to check your answers.)

a. pd.merge(population, countyseats)

| State      | Country     | Year | Population | Statename  | Countryname  | Countryseat |
|------------|-------------|------|------------|------------|--------------|-------------|
| California | Orange      | 2000 | 2846289    | California | Orange       | Santa Ana   |
| California | Orange      | 2000 | 2846289    | California | Los Angeles  | Los Angeles |
| California | Orange      | 2000 | 2846289    | California | San Diego    | San Diego   |
| California | Orange      | 2000 | 2846289    | Oregon     | Wasco        | The Dalles  |
| California | Orange      | 2010 | 3010232    | California | Orange       | Santa Ana   |
| California | Orange      | 2010 | 3010232    | California | Los Angeles  | Los Angeles |
| California | Orange      | 2010 | 3010232    | California | San Diego    | San Diego   |
| California | Orange      | 2010 | 3010232    | Oregon     | Wasco        | The Dalles  |
| California | Los Angeles | 2000 | 3694820    | California | Orange       | Santa Ana   |
| California | Los Angeles | 2000 | 3694820    | California | Los Angeles  | Los Angeles |
| California | Los Angeles | 2000 | 3694820    | California | San Diego    | San Diego   |
| California | Los Angeles | 2000 | 3694820    | Oregon     | Wasco        | The Dalles  |
| California | Los Angeles | 2010 | 3792621    | California | Orange       | Santa Ana   |
| California | Los Angeles | 2010 | 3792621    | California | Los Angeles  | Los Angeles |
| California | Los Angeles | 2010 | 3792621    | California | San Diego    | San Diego   |
| California | Los Angeles | 2010 | 3792621    | Oregon     | Wasco        | The Dalles  |

b. pd.merge(population, countyseats, left_on="state", right_on="statename")

| State      | Country     | Year | Population | Statename  | Countryname  | Countryseat |
|------------|-------------|------|------------|------------|--------------|-------------|
| California | Orange      | 2000 | 2846289    | California | Orange       | Santa Ana   |
| California | Orange      | 2000 | 2846289    | California | Los Angeles  | Los Angeles |
| California | Orange      | 2000 | 2846289    | California | San Diego    | San Diego   |
| California | Orange      | 2010 | 3010232    | California | Orange       | Santa Ana   |
| California | Orange      | 2010 | 3010232    | California | Los Angeles  | Los Angeles |
| California | Orange      | 2010 | 3010232    | California | San Diego    | San Diego   |
| California | Los Angeles | 2000 | 3694820    | California | Orange       | Santa Ana   |
| California | Los Angeles | 2000 | 3694820    | California | Los Angeles  | Los Angeles |
| California | Los Angeles | 2000 | 3694820    | California | San Diego    | San Diego   |
| California | Los Angeles | 2010 | 3792621    | California | Orange       | Santa Ana   |
| California | Los Angeles | 2010 | 3792621    | California | Los Angeles  | Los Angeles |
| California | Los Angeles | 2010 | 3792621    | California | San Diego    | San Diego   |

c. pd.merge(population, countyseats, left_on=["state", "county"], right_on=["statename", "countyname"])

| State      | Country     | Year | Population | Statename  | Countryname  | Countryseat |
|------------|-------------|------|------------|------------|--------------|-------------|
| California | Orange      | 2000 | 2846289    | California | Orange       | Santa Ana   |
| California | Orange      | 2010 | 3010232    | California | Orange       | Santa Ana   |
| California | Los Angeles | 2000 | 3694820    | California | Los Angeles  | Los Angeles |
| California | Los Angeles | 2010 | 3792621    | California | Los Angeles  | Los Angeles |

d. pd.merge(population, countyseats, left_on=["state", "county", "year"], right_on=["statename", "countyname", "countyseat"])

| State      | Country     | Year | Population | Statename  | Countryname  | Countryseat |
|------------|-------------|------|------------|------------|--------------|-------------|
return nothing

# Question 3
Consider the billboard dataset that is supplied with the tidyr package which shows the Billboard top 100 song rankings in the year 2000. Apply the Pandas data wrangling methods to answer these questions. For each question, give the code as a single method chain with multiple “verbs” one after the other, beginning with billboard.

Hints:

- To load datasets from R packages, see Slide 13 of Data wrangling - Pandas.
- Write the code to convert the dataset to a tidy table first.

a. Show for each track, how many weeks it spent on the chart

In [33]:
new_billboard = billboard.melt(
id_vars=['artist','track','date.entered'],
value_vars=billboard.columns.drop([ 'artist','track','date.entered']),
var_name='week',
value_name='rank')
new_billboard['week'] = new_billboard['week'].str.replace('wk', '').astype('Int64')

new_billboard.filter(items=['track', 'week']).groupby('track').count()

                         week
track
(Hot S**t) Country G...    76
3 Little Words             76
911                        76
A Country Boy Can Su...    76
A Little Gasoline          76
...                       ...
You Won't Be Lonely ...    76
You'll Always Be Lov...    76
You're A God               76
Your Everything            76
www.memory                 76

[316 rows x 1 columns]

b. List tracks in decreasing order of number of weeks spent on the chart

In [34]:
new_billboard.sort_values(by='week', ascending=False)

                artist                    track date.entered  week  rank
24090    Zombie Nation            Kernkraft 400   2000-09-02    76   NaN
24061  Third Eye Blind         Never Let You Go   2000-01-22    76   NaN
24070          Tuesday                   I Know   2000-12-30    76   NaN
24085   Worley, Darryl  When You Need My Lov...   2000-06-17    76   NaN
24084      Wills, Mark              Back At One   2000-01-15    76   NaN
...                ...                      ...          ...   ...   ...
115                Guy                  Dancin'   1999-12-18     1  46.0
114       Griggs, Andy               She's More   2000-03-11     1  81.0
21               Avant                Separated   2000-04-29     1  62.0
20               Avant            My First Love   2000-11-04     1  70.0
19       Anthony, Marc           You Sang To Me   2000-02-26     1  77.0

[24092 rows x 5 columns]

c. Show for each track, its top rank

In [37]:
new_billboard.groupby('track').agg({'rank': 'min'})

                         rank
track
(Hot S**t) Country G...   7.0
3 Little Words           89.0
911                      38.0
A Country Boy Can Su...  75.0
A Little Gasoline        75.0
...                       ...
You Won't Be Lonely ...  80.0
You'll Always Be Lov...  55.0
You're A God             23.0
Your Everything          51.0
www.memory               45.0

[316 rows x 1 columns]

d. List tracks in increasing order of its top rank

In [47]:
new_billboard.groupby('track').agg({'rank': 'min'}).sort_values(by='rank',ascending=False).filter(items=['track'])

Empty DataFrame
Columns: []
Index: [Toca's Miracle, Got Beef, Freakin' It, Kernkraft 400, Cherchez LaGhost, Spanish Guitar, I Know, Imagine That, Souljas, Get Up, All Good?, Ta Da, Dancing Queen, Pull Over, No Mercy, Riddle, I'm Outta Love, Do You, Love Sets You Free, L.A. Song, The Quittin' Kind, Baby U Are, 3 Little Words, If You Don't Wanna L..., Got It All, Re-Arranged, Still In My Heart, Don't Call Me Baby, The Hardest Part Of ..., Take That, Me Neither, West Side Story, Can't Stay, Can't Go For That, What Means The World..., U Understand, Shut Up, Straight Up, Real Live Woman, Meanwhile Back At Th..., You Won't Be Lonely ..., Summer Rain, Daddy Won't Sell The..., Sour Girl, The Best Man I Can B..., Monica, No Me Dejes De Quere..., The Rockafeller Skan..., Put Your Hand In Min..., Smoke Rings In The D..., Stay Or Let It Go, Mr. Too Damn Good, I Disappear, My Love Goes On And ..., Hey Papi, It's So Hard, How Many Licks?, When You Need My Lov..., A Little Gasoline, A Country Boy Can Su..., Another Nine Minutes, Whistle While You Tw..., Live, Laugh, Love, No Leaf Clover (Live..., Tricky Tricky, Ryde or Die, Chick, N 2 Gether Now, Left, Right, Left, Sleepwalker, Tha Block Is Hot, Baby Don't Cry (Keep..., Breathe And Stop, I Belong To You, That's The Kind Of M..., Can't Fight The Moon..., Left & Right, My Baby You, Original Prankster, Same Script, Differe..., Californication, Do What You Gotta Do, Deep Inside Of You, If I Am, Give Me You, What's My Name, Private Emotion, Rollin', Cold Day In July, I Need A Hot Girl, More, Do It Again (Put Ya ..., As We Lay, It Was, That Other Woman, You Should've Told M..., Deep Inside, Treat Her Like A Lad..., I Think God Can Expl..., Where You Are, Mirror Mirror, ...]

[316 rows x 0 columns]

e. Show for each artist, their top rank

In [48]:
new_billboard.groupby('artist').agg({'rank': 'min'})

                  rank
artist
2 Pac             72.0
2Ge+her           87.0
3 Doors Down       3.0
504 Boyz          17.0
98^0               2.0
...                ...
Yankee Grey       74.0
Yearwood, Trisha  81.0
Ying Yang Twins   74.0
Zombie Nation     99.0
matchbox twenty    1.0

[228 rows x 1 columns]

f. List artists in increasing order of their top rank

In [51]:
new_billboard.groupby('artist').agg({'rank': 'min'}).sort_values(by='rank',ascending=False).filter(items=['artist'])

Empty DataFrame
Columns: []
Index: [Fragma, Zombie Nation, Smith, Will, Ghostface Killah, Master P, LL Cool J, Tuesday, Larrieux, Amel, De La Soul, Sheist, Shade, Lil' Mo, A*Teens, Trina, En Vogue, Herndon, Ty, Anastacia, Funkmaster Flex, Hart, Beth, Nu Flavor, Tamar, Spencer, Tracie, Madison Avenue, 2Ge+her, Carter, Torrey, Tamia, Hollister, Dave, Juvenile, Moore, Chante, Cam'ron, Trick Daddy, Yearwood, Trisha, Cyrus, Billy Ray, Clark Family Experience, Montgomery Gentry, Stone Temple Pilots, Estefan, Gloria, Before Dark, Allan, Gary, Levert, Gerald, McKnight, Brian, Cagle, Chris, Byrd, Tracy, Fatboy Slim, Big Punisher, Clark, Terri, Worley, Darryl, Yankee Grey, Bega, Lou, Metallica, Ying Yang Twins, Wallflowers, The, Lox, Drama, 2 Pac, Lil Wayne, Q-Tip, Kravitz, Lenny, Loveless, Patty, Offspring, The, Brooks, Garth, Hot Boys, Adkins, Trace, Limp Bizkit, Changing Faces, Price, Kelly, Wright, Chely, Blige, Mary J., Kumbia Kings, Splender, LFO, Lil' Kim, Usher, Puff Daddy, Sister Hazel, Nas, Henley, Don, Diffie, Joe, Shyne, R.E.M., Papa Roach, Adams, Yolanda, Stone, Angie, Brooks & Dunn, Kelis, Beenie Man, Williams, Robbie, Gill, Vince, Bloodhound Gang, Urban, Keith, TLC, Lopez, Jennifer, Heatherly, Eric, John, Elton, Pearl Jam, Davidson, Clay, Ginuwine, Ideal, Eastsidaz, The, Common, Black, Clint, ...]

[228 rows x 0 columns]

g. List tracks that spent more than 35 weeks in the charts

In [52]:
new_billboard.groupby('track').agg({'week': 'max'}).query('week > 35')

/tmp/ipykernel_6745/2568907537.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  new_billboard.groupby('track').agg({'week': 'max'}).query('week > 35')

                         week
track
(Hot S**t) Country G...    76
3 Little Words             76
911                        76
A Country Boy Can Su...    76
A Little Gasoline          76
...                       ...
You Won't Be Lonely ...    76
You'll Always Be Lov...    76
You're A God               76
Your Everything            76
www.memory                 76

[316 rows x 1 columns]

h. List tracks that spent more than 35 weeks in the charts along with their artists

In [60]:
new_billboard.groupby(['track', 'artist']).agg({'week': 'max'}).query('week > 35')

/tmp/ipykernel_6745/4132413919.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  new_billboard.groupby(['track', 'artist']).agg({'week': 'max'}).query('week > 35')

                                          week
track                   artist
(Hot S**t) Country G... Nelly               76
3 Little Words          Nu Flavor           76
911                     Jean, Wyclef        76
A Country Boy Can Su... Brock, Chad         76
A Little Gasoline       Clark, Terri        76
...                                        ...
You Won't Be Lonely ... Cyrus, Billy Ray    76
You'll Always Be Lov... Brooks & Dunn       76
You're A God            Vertical Horizon    76
Your Everything         Urban, Keith        76
www.memory              Jackson, Alan       76

[317 rows x 1 columns]

# Question 4
The demographics.csv  file (available in the Tidy data module on Canvas) gives the proportion of a country’s population in different age groups and some other demographic data such as mortality rates and expected lifetime. You can read a CSV file into a DataFrame using Pandas read_csv(), like so: demo = pd.read_csv("demographics.csv")

In [18]:
import pandas as pd

demo = pd.read_csv('/content/demographics.csv')
demo

,Country Name,Country Code,Series Name,Series Code,YR2015
0,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,63.377
1,Afghanistan,AFG,Urban population,SP.URB.TOTL,8535606
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,34413603
3,Afghanistan,AFG,"Population ages 80 and above, female",SP.POP.80UP.FE,48319
4,Afghanistan,AFG,"Population ages 80 and above, male",SP.POP.80UP.MA,37233
...,...,...,...,...,...
3880,Zimbabwe,ZWE,"Mortality rate, adult, male (per 1,000 male ad...",SP.DYN.AMRT.MA,396.789
3881,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,7245857
3882,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,6568772
3883,Zimbabwe,ZWE,"Population ages 65 and above, female",SP.POP.65UP.FE.IN,254913
3884,Zimbabwe,ZWE,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,138008

a. The data is not “tidy”. In 2-3 sentences, explain why.

**The data isn't tidy becuase the Series Name column has many variables stored as row values instead of being in their own column. Also, the values, such as YR2015, are stored as column headers. Raw population counts are mixed in with other values, like mortality rates and life expectancy in the same dataset.**

b. Transform the table to tidy data with one country per row.

In [19]:
pd.melt(demo, id_vars=['Country Name', 'Series Name', 'Series Code'], var_name='Year', value_name='Value')

,Country Name,Series Name,Series Code,Year,Value
0,Afghanistan,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,Country Code,AFG
1,Afghanistan,Urban population,SP.URB.TOTL,Country Code,AFG
2,Afghanistan,"Population, total",SP.POP.TOTL,Country Code,AFG
3,Afghanistan,"Population ages 80 and above, female",SP.POP.80UP.FE,Country Code,AFG
4,Afghanistan,"Population ages 80 and above, male",SP.POP.80UP.MA,Country Code,AFG
...,...,...,...,...,...
7765,Zimbabwe,"Mortality rate, adult, male (per 1,000 male ad...",SP.DYN.AMRT.MA,YR2015,396.789
7766,Zimbabwe,"Population, female",SP.POP.TOTL.FE.IN,YR2015,7245857
7767,Zimbabwe,"Population, male",SP.POP.TOTL.MA.IN,YR2015,6568772
7768,Zimbabwe,"Population ages 65 and above, female",SP.POP.65UP.FE.IN,YR2015,254913
7769,Zimbabwe,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,YR2015,138008

c. Add the male/female population numbers together (i.e., ignore sex-related differences). [Hint: You will have to assign for every pair of columns, e.g., .assign(**{'SP.POP.0014.IN': lambda df: df['SP.POP.0014.MA.IN'] + df['SP.POP.0014.FE.IN']})]

In [20]:
tidy_demo = demo.pivot(index=['Country Name', 'Country Code'], columns='Series Code', values='YR2015').reset_index()

for col in tidy_demo.columns:
    if col not in ['Country Name', 'Country Code']:
        tidy_demo[col] = pd.to_numeric(tidy_demo[col], errors='coerce')

tidy_demo = tidy_demo.assign(
    **{
        'SP.POP.0014.IN': lambda df: df['SP.POP.0014.MA.IN'] + df['SP.POP.0014.FE.IN'],
        'SP.POP.1564.IN': lambda df: df['SP.POP.1564.MA.IN'] + df['SP.POP.1564.FE.IN'],
        'SP.POP.65UP.IN': lambda df: df['SP.POP.65UP.MA.IN'] + df['SP.POP.65UP.FE.IN'],
        'SP.POP.80UP.IN': lambda df: df['SP.POP.80UP.MA'] + df['SP.POP.80UP.FE']
    }
)

display(tidy_demo.head())

Series Code,Country Name,Country Code,SP.DYN.AMRT.FE,SP.DYN.AMRT.MA,SP.DYN.LE00.IN,SP.POP.0014.FE.IN,SP.POP.0014.MA.IN,SP.POP.1564.FE.IN,SP.POP.1564.MA.IN,SP.POP.65UP.FE.IN,...,SP.POP.80UP.FE,SP.POP.80UP.MA,SP.POP.TOTL,SP.POP.TOTL.FE.IN,SP.POP.TOTL.MA.IN,SP.URB.TOTL,SP.POP.0014.IN,SP.POP.1564.IN,SP.POP.65UP.IN,SP.POP.80UP.IN
0,Afghanistan,AFG,206.746,248.724,63.377,7538168.0,7905639.0,8730445.0,9386355.0,458824.0,...,48319.0,37233.0,34413603.0,16727437.0,17686166.0,8535606.0,15443807.0,18116800.0,852996.0,85552.0
1,Albania,ALB,51.195,99.215,78.025,252745.0,285043.0,972981.0,1006194.0,188520.0,...,37747.0,29218.0,2880703.0,1414246.0,1466457.0,1654503.0,537788.0,1979175.0,363740.0,66965.0
2,Algeria,DZA,84.440,107.191,76.090,5583284.0,5821646.0,12878041.0,13115548.0,1202806.0,...,238417.0,215324.0,39728025.0,19664131.0,20063894.0,28146511.0,11404930.0,25993589.0,2329506.0,453741.0
3,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,55812.0,NaN,NaN,48689.0,NaN,NaN,NaN,NaN
4,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,78011.0,NaN,NaN,68919.0,NaN,NaN,NaN,NaN

d. Write code to show the top 5 countries with the lowest proportion of the population below 14 years old (i.e., SP.POP.0014.IN/SP.POP.TOTL) [Code, and list of 5 countries]

In [21]:
(
    tidy_demo
    .assign(proportion_below_14=tidy_demo['SP.POP.0014.IN'] / tidy_demo['SP.POP.TOTL'])
    .sort_values(by='proportion_below_14')
)

Series Code,Country Name,Country Code,SP.DYN.AMRT.FE,SP.DYN.AMRT.MA,SP.DYN.LE00.IN,SP.POP.0014.FE.IN,SP.POP.0014.MA.IN,SP.POP.1564.FE.IN,SP.POP.1564.MA.IN,SP.POP.65UP.FE.IN,...,SP.POP.80UP.MA,SP.POP.TOTL,SP.POP.TOTL.FE.IN,SP.POP.TOTL.MA.IN,SP.URB.TOTL,SP.POP.0014.IN,SP.POP.1564.IN,SP.POP.65UP.IN,SP.POP.80UP.IN,proportion_below_14
101,"Hong Kong SAR, China",HKG,35.191,66.094,84.278049,383811.0,430450.0,2935546.0,2434210.0,589725.0,...,126766.0,7291300.0,3909083.0,3382217.0,7291300.0,814261.0,5369756.0,1107282.0,322161.0,0.111676
140,"Macao SAR, China",MAC,25.663,61.155,83.707000,36749.0,39207.0,249081.0,225318.0,27419.0,...,4112.0,602085.0,313248.0,288837.0,602085.0,75956.0,474399.0,51731.0,11981.0,0.126155
205,Singapore,SGP,37.554,64.369,82.743902,340747.0,358442.0,2021032.0,2314018.0,276642.0,...,37545.0,5535002.0,2638421.0,2896581.0,5535002.0,699189.0,4335050.0,500763.0,101088.0,0.126321
113,Japan,JPN,37.102,69.979,83.793902,8035159.0,8479674.0,38195060.0,39349870.0,18786503.0,...,3353859.0,127141000.0,65016722.0,62124278.0,116182717.0,16514833.0,77544930.0,33081237.0,9645027.0,0.129894
86,Germany,DEU,50.173,92.460,80.641463,5244648.0,5551821.0,26460588.0,27096808.0,9806374.0,...,1647555.0,81686611.0,41511610.0,40175001.0,63062064.0,10796469.0,53557396.0,17332746.0,4658757.0,0.132169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Sint Maarten (Dutch part),SXM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,38825.0,NaN,NaN,38825.0,NaN,NaN,NaN,NaN,NaN
218,St. Kitts and Nevis,KNA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,51203.0,NaN,NaN,15784.0,NaN,NaN,NaN,NaN,NaN
220,St. Martin (French part),MAF,NaN,NaN,79.470732,NaN,NaN,NaN,NaN,NaN,...,NaN,35858.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,Turks and Caicos Islands,TCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,35981.0,NaN,NaN,33173.0,NaN,NaN,NaN,NaN,NaN
241,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11099.0,NaN,NaN,6629.0,NaN,NaN,NaN,NaN,NaN